### ISSUE TITLE
pyproject.toml: A Simple Structure

### ISSUE THREAD

**Issue by Proteusiq** [Proteusiq/dotfiles#85]
```toml
[project]
name = "gone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.ruff.lint]
select = [
	  "A", # warn about shadowing built-ins
	  "E", # style stuff, whitespaces
	  "F", # important pyflakes lints
	  "I", # import sorting
	  "N", # naming
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.9.5",
]
```
